apiVersion: v1
kind: Secret
metadata:
  name: cloudprofiles-values
  namespace: flux-system
type: Opaque
stringData:
  values.yaml: |
    global:
      kubernetes:
        versions:
          1.30.5:
            classification: supported
      seedSelector:
        enabled: true
        selector:
          providerTypes:
            - openstack
